#!/bin/bash
# NEXTFLOW TASK: samtools_variant_call (1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 2 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

function nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /BiO/BioPeople/brandon/workflow/nextflow/variant/work/a5/029af9ea598ab62b8432aaf7178cf1/.exitcode
  set +u
  [[ "$COUT" ]] && rm -f "$COUT" || true
  [[ "$CERR" ]] && rm -f "$CERR" || true
  exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /BiO/BioPeople/brandon/workflow/nextflow/variant/work/a5/029af9ea598ab62b8432aaf7178cf1/.command.begin
[ -f /BiO/BioPeople/brandon/workflow/nextflow/variant/work/a5/029af9ea598ab62b8432aaf7178cf1/.command.env ] && source /BiO/BioPeople/brandon/workflow/nextflow/variant/work/a5/029af9ea598ab62b8432aaf7178cf1/.command.env
rm -f TN1602D0552.dedup.bam
ln -s /BiO/BioProjects/TBD160423-Cow-WES-2016-07/result/07-1_picard_dedup/TN1602D0552/TN1602D0552.dedup.bam TN1602D0552.dedup.bam


set +e
COUT=$PWD/.command.po; mkfifo "$COUT"
CERR=$PWD/.command.pe; mkfifo "$CERR"
tee .command.out < "$COUT" &
tee1=$!
tee .command.err < "$CERR" >&2 &
tee2=$!
(
/bin/bash -ue /BiO/BioPeople/brandon/workflow/nextflow/variant/work/a5/029af9ea598ab62b8432aaf7178cf1/.command.sh
) >"$COUT" 2>"$CERR" &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
